# Generated by Django 3.0.5 on 2020-05-21 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200521_1203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='name',
            new_name='fullname',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='user_id',
            new_name='username',
        ),
    ]
